# fly.toml app configuration file generated for sveltekit-demo-bot on 2024-04-09T15:12:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sveltekit-demo-bot'
primary_region = 'sjc'

[build]
  image = '7b27e378'

[env]
  CATALYST_SVELTEKIT_DEMO_BASE_URL = 'https://catalyst-sveltekit-example.vercel.app/'

[[vm]]
  memory = '768mb'
  cpu_kind = 'shared'
  cpus = 1
